---
  - name: Installing and Launching Filebeat
    hosts: webservers
    become: yes
    tasks:

    - name: Download Filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: Install Filebeat deb
      command: dpkg -i filebeat-7.6.1-amd64.deb

    - name: Drop in Filebeat Config
      copy:
        src: /etc/ansible/files/filebeat-config_v1.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable and Configure Filebeat Module
      command: filebeat modules enable system

    - name: Setup Filebeat
      command: filebeat setup

    - name: Start Filebeat Service
      command: service filebeat start

